apiVersion: cnm.juniper.net/v1
kind: BgpRouterGroup
metadata:
  name: crpd2
spec:
  discover: true
  selector:
    matchLabels:
      name: crpd1
  bgpRouterTemplate:
    managed: true
    routerType: Crpd
    autonomousSystemNumber: 1
    addressFamilies:
    - Inet
